import { PowertrainType } from './providers/interfaces';

export interface CarPreset {
  id: string;
  rank?: number;
  makeModel: string;
  segment: string;
  engine: string;
  fuelType: 'petrol' | 'diesel';
  powertrain: PowertrainType;
  defaultConsumption: number;
  consumptionRange: string;
}

export const POPULAR_CARS: CarPreset[] = [
  {
    id: 'audi-q2',
    makeModel: 'Audi Q2',
    segment: 'B-SUV',
    engine: '1.5 35 TFSI (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.4,
    consumptionRange: '5.2 - 5.8 L / 100km',
  },
  {
    id: 'renault-clio',
    rank: 1,
    makeModel: 'Renault Clio HB',
    segment: 'B-Hatchback',
    engine: '1.0 TCe (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.3,
    consumptionRange: '5.0 - 5.5 L / 100km',
  },
  {
    id: 'toyota-corolla-hybrid',
    rank: 2,
    makeModel: 'Toyota Corolla (Hybrid)',
    segment: 'C-Sedan',
    engine: '1.8 Hybrid',
    fuelType: 'petrol',
    powertrain: 'full_hybrid',
    defaultConsumption: 4.5,
    consumptionRange: '4.0 - 5.0 L / 100km',
  },
  {
    id: 'toyota-corolla-petrol',
    rank: 2,
    makeModel: 'Toyota Corolla (Petrol)',
    segment: 'C-Sedan',
    engine: '1.5 Dynamic Force (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.8,
    consumptionRange: '5.5 - 6.2 L / 100km',
  },
  {
    id: 'renault-megane',
    rank: 3,
    makeModel: 'Renault Megane Sedan',
    segment: 'C-Sedan',
    engine: '1.3 TCe (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.9,
    consumptionRange: '5.5 - 6.5 L / 100km',
  },
  {
    id: 'toyota-chr',
    rank: 4,
    makeModel: 'Toyota C-HR',
    segment: 'C-SUV',
    engine: '1.8 Hybrid',
    fuelType: 'petrol',
    powertrain: 'full_hybrid',
    defaultConsumption: 4.9,
    consumptionRange: '4.8 - 5.3 L / 100km',
  },
  {
    id: 'renault-duster-diesel',
    rank: 5,
    makeModel: 'Renault Duster (Diesel)',
    segment: 'C-SUV',
    engine: '1.5 Blue dCi (Diesel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 5.3,
    consumptionRange: '5.0 - 5.8 L / 100km',
  },
  {
    id: 'renault-duster-petrol',
    rank: 5,
    makeModel: 'Renault Duster (Petrol)',
    segment: 'C-SUV',
    engine: '1.3 TCe (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.2,
    consumptionRange: '5.8 - 6.5 L / 100km',
  },
  {
    id: 'hyundai-i20',
    rank: 6,
    makeModel: 'Hyundai i20',
    segment: 'B-Hatchback',
    engine: '1.4 MPI (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.5,
    consumptionRange: '6.0 - 7.5 L / 100km',
  },
  {
    id: 'vw-taigo',
    rank: 7,
    makeModel: 'Volkswagen Taigo',
    segment: 'B-SUV',
    engine: '1.0 TSI (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.5,
    consumptionRange: '5.0 - 6.0 L / 100km',
  },
  {
    id: 'fiat-egea-diesel',
    rank: 8,
    makeModel: 'Fiat Egea Sedan (Diesel)',
    segment: 'C-Sedan',
    engine: '1.3 / 1.6 Multijet (Diesel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 4.7,
    consumptionRange: '4.5 - 5.3 L / 100km',
  },
  {
    id: 'fiat-egea-petrol',
    rank: 8,
    makeModel: 'Fiat Egea Sedan (Petrol)',
    segment: 'C-Sedan',
    engine: '1.4 Fire (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.4,
    consumptionRange: '6.0 - 7.0 L / 100km',
  },
  {
    id: 'peugeot-2008',
    rank: 9,
    makeModel: 'Peugeot 2008',
    segment: 'B-SUV',
    engine: '1.2 PureTech (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.8,
    consumptionRange: '5.5 - 6.5 L / 100km',
  },
  {
    id: 'fiat-egea-cross-diesel',
    rank: 10,
    makeModel: 'Fiat Egea Cross (Diesel)',
    segment: 'C-SUV',
    engine: '1.6 Multijet (Diesel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 5.0,
    consumptionRange: '4.8 - 5.6 L / 100km',
  },
  {
    id: 'fiat-egea-cross-petrol',
    rank: 10,
    makeModel: 'Fiat Egea Cross (Petrol)',
    segment: 'C-SUV',
    engine: '1.4 Fire (Petrol)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.6,
    consumptionRange: '6.0 - 7.5 L / 100km',
  },
];
