import { PowertrainType } from './providers/interfaces';

export interface CarPreset {
  id: string;
  rank?: number;
  brand: string;
  makeModel: string;
  segment: string;
  engine: string;
  fuelType: 'petrol' | 'diesel';
  powertrain: PowertrainType;
  defaultConsumption: number;
  consumptionRange: string;
  popularRankTitle?: string;
}

export const CAR_BRANDS = [
  'All',
  'Renault',
  'Toyota',
  'Fiat',
  'Volkswagen',
  'Peugeot',
  'Hyundai',
  'Audi',
] as const;

export const POPULAR_CARS: CarPreset[] = [
  {
    id: 'renault-clio',
    rank: 1,
    brand: 'Renault',
    makeModel: 'Renault Clio HB',
    segment: 'B-Hatchback',
    engine: '1.0 TCe (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.3,
    consumptionRange: '5.0 - 5.5 L / 100km',
    popularRankTitle: '#1 Türkiye En Çok Satan',
  },
  {
    id: 'toyota-corolla-hybrid',
    rank: 2,
    brand: 'Toyota',
    makeModel: 'Toyota Corolla Hybrid',
    segment: 'C-Sedan',
    engine: '1.8 Hybrid',
    fuelType: 'petrol',
    powertrain: 'full_hybrid',
    defaultConsumption: 4.5,
    consumptionRange: '4.0 - 5.0 L / 100km',
    popularRankTitle: '#2 Hibrit Lideri',
  },
  {
    id: 'toyota-corolla-petrol',
    rank: 2,
    brand: 'Toyota',
    makeModel: 'Toyota Corolla 1.5',
    segment: 'C-Sedan',
    engine: '1.5 Dynamic Force (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.8,
    consumptionRange: '5.5 - 6.2 L / 100km',
  },
  {
    id: 'renault-megane',
    rank: 3,
    brand: 'Renault',
    makeModel: 'Renault Megane Sedan',
    segment: 'C-Sedan',
    engine: '1.3 TCe (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.9,
    consumptionRange: '5.5 - 6.5 L / 100km',
    popularRankTitle: '#3 Filo & Aile Favorisi',
  },
  {
    id: 'fiat-egea-diesel',
    rank: 4,
    brand: 'Fiat',
    makeModel: 'Fiat Egea Sedan Dizel',
    segment: 'C-Sedan',
    engine: '1.3 / 1.6 Multijet (Dizel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 4.7,
    consumptionRange: '4.5 - 5.3 L / 100km',
    popularRankTitle: 'Ekonomik Dizel',
  },
  {
    id: 'fiat-egea-petrol',
    rank: 4,
    brand: 'Fiat',
    makeModel: 'Fiat Egea Sedan Benzin',
    segment: 'C-Sedan',
    engine: '1.4 Fire (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.4,
    consumptionRange: '6.0 - 7.0 L / 100km',
  },
  {
    id: 'fiat-egea-cross-diesel',
    rank: 5,
    brand: 'Fiat',
    makeModel: 'Fiat Egea Cross Dizel',
    segment: 'C-Crossover',
    engine: '1.6 Multijet (Dizel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 5.0,
    consumptionRange: '4.8 - 5.6 L / 100km',
  },
  {
    id: 'fiat-egea-cross-petrol',
    rank: 5,
    brand: 'Fiat',
    makeModel: 'Fiat Egea Cross Benzin',
    segment: 'C-Crossover',
    engine: '1.4 Fire (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.6,
    consumptionRange: '6.0 - 7.5 L / 100km',
  },
  {
    id: 'toyota-chr',
    rank: 6,
    brand: 'Toyota',
    makeModel: 'Toyota C-HR Hybrid',
    segment: 'C-SUV',
    engine: '1.8 Hybrid',
    fuelType: 'petrol',
    powertrain: 'full_hybrid',
    defaultConsumption: 4.9,
    consumptionRange: '4.8 - 5.3 L / 100km',
  },
  {
    id: 'renault-duster-diesel',
    rank: 7,
    brand: 'Renault',
    makeModel: 'Renault Duster Dizel',
    segment: 'C-SUV',
    engine: '1.5 Blue dCi (Dizel)',
    fuelType: 'diesel',
    powertrain: 'diesel',
    defaultConsumption: 5.3,
    consumptionRange: '5.0 - 5.8 L / 100km',
  },
  {
    id: 'renault-duster-petrol',
    rank: 7,
    brand: 'Renault',
    makeModel: 'Renault Duster 1.3 TCe',
    segment: 'C-SUV',
    engine: '1.3 TCe (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.2,
    consumptionRange: '5.8 - 6.5 L / 100km',
  },
  {
    id: 'peugeot-2008',
    rank: 8,
    brand: 'Peugeot',
    makeModel: 'Peugeot 2008',
    segment: 'B-SUV',
    engine: '1.2 PureTech (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.8,
    consumptionRange: '5.5 - 6.5 L / 100km',
  },
  {
    id: 'hyundai-i20',
    rank: 9,
    brand: 'Hyundai',
    makeModel: 'Hyundai i20',
    segment: 'B-Hatchback',
    engine: '1.4 MPI (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 6.5,
    consumptionRange: '6.0 - 7.5 L / 100km',
  },
  {
    id: 'vw-taigo',
    rank: 10,
    brand: 'Volkswagen',
    makeModel: 'Volkswagen Taigo',
    segment: 'B-SUV',
    engine: '1.0 TSI (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.5,
    consumptionRange: '5.0 - 6.0 L / 100km',
  },
  {
    id: 'audi-q2',
    brand: 'Audi',
    makeModel: 'Audi Q2',
    segment: 'B-SUV',
    engine: '1.5 35 TFSI (Benzin)',
    fuelType: 'petrol',
    powertrain: 'petrol',
    defaultConsumption: 5.4,
    consumptionRange: '5.2 - 5.8 L / 100km',
  },
];
